version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    context: requirements/mariadb
    dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
  nginx:
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    context: requirements/nginx
    dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: on-failure
  wordpress:
    container_name: wordpress
    networks:
      - inception
    context: requirements/wordpress
    dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"
    
volumes:
  mariadb:
    driver: local
    driver_opts:
    type: none
    device: /Users/hgeissle/data/mariadb
    o: bind
  wordpress:
    driver: local
    driver_opts:
    type: none
    device: /Users/hgeissle/data/wordpress
    o: bind

networks:
  inception:
  driver: bridge