version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: on-failure
  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/hadrien/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/hadrien/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge